### ISSUE TITLE
How to handle resources correctly

### ISSUE THREAD

**Issue by spadgeaki** [faceyspacey/redux-first-router-demo#28]
Hi, thank you for creating great stack of tools for React @faceyspacey. Anyway I have a question about managing resources (images, videos, etc.) while using this setup. I know that its more of a webpack question but I am currious how you deal with it. 

I started including png images to my new project which is based on this demo. So I added file-loader to both **webpack/server.prod.js** and **webpack/client.prod.js** and set it up to manage PNGs. But images are processed during building of both parts - server and client. When I have more images and use plugins like imagemin-webpack-plugin to process them then it takes really long time and every resource is placed in both **buildClient/** and **buildServer/** folders, which is unnessecary.

Do you have any advice for me? Is my question clear enough or should I upload an example project?

**Comment by faceyspacey** [comment]
host images in the cloud very early on. i never use the image loaders. i put my images on S3 from the start of all my apps. then use cloudinary for transformations: https://cloudinary.com

...otherwise, you will notice that for CSS we don't generate stylesheets on the server. we only transform the classNames in javascript modules:

https://github.com/faceyspacey/redux-first-router-demo/blob/master/webpack/server.dev.js#L48

...so perhaps for images there's a similar solution. i.e. to do the minimal amount of work so your react component code is generated correctly, without actually creating the images. A solution like that is most likely what you're looking for. I don't know what it is though :)
