### ISSUE TITLE
Add Flow

### ISSUE THREAD

**Issue by corydeppen** [faceyspacey/redux-first-router-demo#5]
I think it would be beneficial to add Flow (and perhaps a TypeScript version?) to this demo project. I've been trying to add RFR to a TypeScript project I'm working on and have been noticing some potential issues with the definitions. When I refer to the Flow definitions and to the example project, I've noticed inconsistencies with the types. By adding Flow to this project, it should help improve the Flow definitions, which could help improve the TypeScript definitions.

Since I'm very interested in this project, as well as interested in learning more about Flow and TypeScript, I'd be happy to help with adding Flow if it's something you think would add value.

**Comment by faceyspacey** [comment]
I'm all for it, especially Flow. use the @next version. It has query support and i fixed 2 flow errors that occurred as a result of new versions of Flow. 

I think we also need to add the flow definitions to flow-typed, as it addresses a few things you can't address by shipping `.flow` versions of files as we currently do. So that might be a first priority if you ran into issues. It would close this Issue by the way: https://github.com/faceyspacey/redux-first-router/issues/26

For example, if you have `$FlowIssue` to suppress a comment, but then in userland, the user doesnt have that in their `.flowconfig` it won't be suppressed.
